packages:
  - 'apps/*'
  - 'packages/*'
overrides:
  '@fastify/middie': '>=9.3.2'
  next: '>=15.3.6'
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  '@sentry-internal/node-cpu-profiler': false
  '@swc/core': true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
